version: "3.8"

services:
  app:
    image: robsluna/domino-game:5.0.23
    networks:
      - domino-net
      - public-proxy-v2
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://domino:SeducDomin0@postgres:5432/domino_db?schema=public
      - NODE_ENV=production
    volumes:
      - domino_uploads:/app/backend/uploads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "2.0"       # Aumentado para lidar com conexões via Socket/Tempo real
          memory: 4G        # Aumentado para 4GB para evitar quedas em picos de uso
        reservations:
          memory: 512M      # Reserva mínima garantida
      labels:
        - "traefik.enable=true"
        # Dominio Principal
        - "traefik.http.routers.domino.rule=Host(`games.portaleducampina.com.br`)"
        - "traefik.http.routers.domino.entrypoints=websecure"
        - "traefik.http.routers.domino.tls.certresolver=letsencryptresolver"
        # Servico
        - "traefik.http.services.domino.loadbalancer.server.port=3001"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    networks:
      - domino-net
      - public-proxy-v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 1G        # 1GB para cache de sessões de jogo
        reservations:
          memory: 128M

  postgres:
    image: postgres:16-alpine
    networks:
      - domino-net
      - public-proxy-v2
    environment:
      POSTGRES_DB: domino_db
      POSTGRES_USER: domino
      POSTGRES_PASSWORD: SeducDomin0
    volumes:
      - domino_pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          # Garante que os dados ficam sempre no mesmo nó
          - node.role == manager
      resources:
        limits:
          cpus: "2.0"       # Aumentado de 0.3 para 2.0
          memory: 4G        # Aumentado de 256MB para 4GB
        reservations:
          memory: 512M

networks:
  public-proxy-v2:
    external: true
  domino-net:
    driver: overlay
    attachable: true

volumes:
  domino_pgdata:
    driver: local
  domino_uploads:
    driver: local
