version: "3.8"

services:
  app:
    image: robsluna/domino-game:latest
    networks:
      - public-proxy-v2
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://domino:SeducDomin0@postgres:5432/domino_db?schema=public
      - NODE_ENV=production
    volumes:
      - domino_uploads:/app/backend/uploads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # Dominio Principal
        - "traefik.http.routers.domino.rule=Host(`games.portaleducampina.com.br`)"
        - "traefik.http.routers.domino.entrypoints=websecure"
        - "traefik.http.routers.domino.tls.certresolver=letsencryptresolver"
        # Servico
        - "traefik.http.services.domino.loadbalancer.server.port=3001"
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    networks:
      - public-proxy-v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
          cpus: "0.2"

  postgres:
    image: postgres:16-alpine
    networks:
      - public-proxy-v2
    environment:
      POSTGRES_DB: domino_db
      POSTGRES_USER: domino
      POSTGRES_PASSWORD: SeducDomin0
    volumes:
      - domino_pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          # Garante que os dados ficam sempre no mesmo nó
          - node.role == manager
      resources:
        limits:
          memory: 256M
          cpus: "0.3"

networks:
  public-proxy-v2:
    external: true

volumes:
  domino_pgdata:
    driver: local
  domino_uploads:
    driver: local
